services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 67
        published: 67
        protocol: udp
        mode: host
    environment:
      - TZ=America/Toronto
      - WEBPASSWORD_FILE=/run/secrets/pihole-webpass
    volumes:
      - /mnt/pihole/data:/data
      - /mnt/pihole/dnsmaq.d:/dnsmasq.d
    networks:
      - traefik_proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pihole-secure.rule=Host(`pihole.manly.dylangroff.com`)"
        - "traefik.http.routers.pihole-secure.service=pihole"
        - "traefik.http.services.pihole.loadbalancer.server.port=80"
networks:
  traefik_proxy:
    external: true