services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "888:80"
    environment:
      - TZ=America/Toronto
    volumes:
      - /mnt/pihole/etc:/etc/pihole
      - /mnt/pihole/dns:/dnsmasq.d
    networks:
      - traefik_proxy
    cap_add:
      - SYS_TIME
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pihole-secure.rule=Host(`pihole.manly.dylangroff.com`)"
        - "traefik.http.routers.pihole-secure.entrypoints=websecure"
        - "traefik.http.routers.pihole-secure.service=pihole"
        - "traefik.http.services.pihole.loadbalancer.server.port=80"
networks:
  traefik_proxy:
    external: true