services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 67
        published: 67
        protocol: udp
        mode: host
    environment:
      - TZ=America/Toronto
      - WEBPASSWORD_FILE=/run/secrets/web_pass
    volumes:
      - type: bind
        source: /mnt/Pihole
        target: /data
      - type: bind
        source: /mnt/Pihole
        target: /dnsmasq.d
    secrets:
      - web_pass
    networks:
      - traefik_proxy
    restart: unless-stopped
    deploy:
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik_proxy'
        - 'traefik.http.routers.pihole.rule=Host(`pihole.manly.dylangroff.com`)'
        - 'traefik.http.routers.pihole.tls=true'
        - 'traefik.http.routers.pihole.tls.certresolver=letsencrypt'
        - 'traefik.http.services.pihole-srv.loadbalancer.server.port=80'
networks:
  traefik_proxy:
    external: true
secrets:
  web_pass:
    file: mnt/Pihole/web_pass