---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`pihole.manly.dylangroff.com`)
      services:
        - name: pihole
          port: 80
      middlewares:
        - name: default-headers
  tls:
    store:
      name: default-cloudflare-tls