---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-ncdg
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-pepsichillzone
  storageClassName: smb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ncdg-config
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi