apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: prodissuer
  namespace: default
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: servicekey
      key: key
