services:
  db:
    image: mariadb:lts-noble
    command: --transaction-isolation=READ-COMMITTED
    networks:
      - nextcloud
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_USER_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER_PASSWORD
      
  app:
    image: nextcloud
    networks:
      - nextcloud
      - traefik_proxy
    volumes:
      - ./app:/var/www/html
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER_PASSWORD
      - NEXTCLOUD_ADMIN_PASSWORD
      - SMTP_PASSWORD
    depends_on:
      - db
      - redis
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextcloud-secure.rule=Host(`files.dylangroff.com`)"
        - "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
        - "traefik.http.routers.nextcloud-secure.middlewares=nextcloud-dav-redirect@file"
        - "traefik.http.routers.nextcloud-secure.service=nextcloud"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
  
  redis:
    image: redis:alpine
    networks:
      - nextcloud
    ports:
      6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/usr/local/etc/redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  appapi-dsp:
    image: ghcr.io/nextcloud/nextcloud-appapi-dsp:main
    networks:
      - nextcloud
    ports:
      - 8780:8780
      - 8782:8782
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NC_HAPROXY_PASSWORD=/run/secrets/HP_SHARED_KEY
    secrets:
      - HP_SHARED_KEY

secrets:
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/MYSQL_ROOT_PASSWORD
  MYSQL_USER_PASSWORD:
    file: ./secrets/MYSQL_USER_PASSWORD
  NEXTCLOUD_ADMIN_PASSWORD:
    file: ./secrets/NEXTCLOUD_ADMIN_PASSWORD
  HP_SHARED_KEY:
    file: ./secrets/HP_SHARED_KEY
  SMTP_PASSWORD:
    file: ./secrets/SMTP_PASSWORD

networks:
  nextcloud:
    external: true
  traefik_proxy:
    external: true