services:
  app:
    image: ghcr.io/linuxserver/nextcloud
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Toronto
    volumes:
      - /mnt/dg-nextcloud/app/config:/config
      - /mnt/dg-nextcloud/app/data:/data
    networks:
      - traefik_proxy
      - dg-nextcloud
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dgnc-secure.rule=Host(`nextcloud.manly.dylangroff.com`)"
        - "traefik.http.routers.dgnc-secure.entrypoints=websecure"
        - "traefik.http.routers.dgnc-secure.middlewares=nextcloud-dav-redirect@file"
        - "traefik.http.routers.dgnc-secure.tls.certresolver=cloudflare"
        - "traefik.http.routers.dgnc-secure.service=dgnc"
        - "traefik.http.services.dgnc.loadbalancer.server.port=80"
    depends_on:
      - mariadb
      - redis
  mariadb:
    image: docker.io/mariadb:10.5
    environment:
      - TZ=America/Toronto
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/ncdg_mysql_root_pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD_FILE=/run/secrets/ncdg_mysql_user_pass
    volumes:
      - /mnt/dg-nextcloud/mariadb/config:/etc/mysql/conf.d
      - /mnt/dg-nextcloud/mariadb/mysql-data:/var/lib/mysql
    networks:
      - dg-nextcloud
    secrets:
      - ncdg_mysql_root_pass
      - ncdg_mysql_user_pass
  redis:
    image: docker.io/redis:6-alpine
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - /mnt/dg-nextcloud/redis/config:/usr/local/etc/redis
      - /mnt/dg-nextcloud/redis/redis-data:/data
    networks:
      - dg-nextcloud

networks:
  traefik_proxy:
    external: true
  dg-nextcloud:
    external: true

secrets:
  mysql_root_pass:
    file: /mnt/dg-nextcloud/secrets/mysql_root_pass
  mysql_user_pass:
    file: /mnt/dg-nextcloud/secrets/mysql_user_pass