apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin-ca-issuer
  namespace: origin-ca-issuer
spec:
  selector:
    matchLabels:
      app: origin-ca-issuer
  replicas: 1
  template:
    metadata:
      labels:
        app: origin-ca-issuer
    spec:
      serviceAccountName: originissuer-control
      containers:
        - name: origin-ca-controller
          image: cloudflare/origin-ca-issuer:v0.12.1
          args:
            - --cluster-resource-namespace=$(POD_NAMESPACE)
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "1"
              memory: 512Mi
      terminationGracePeriodSeconds: 10
