---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  cloudflare-token: MjmybqQTrxPHxX9SLw8ezUv9Nja-okqo5e1wb8VT # MUST be an API token, NOT a Global API key!!! https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens